import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/navigation/Navigation';
import AuthProvider from '@/components/auth/AuthProvider';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/theme-provider';
import ChatSupport from '@/components/chat-support';
import MobileNavigation from '@/components/mobileNavigation/MobileNavigation';

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
		>
			<body
				className={`${poppins.variable} antialiased`}
				suppressHydrationWarning
			>
				<main className='container mx-auto min-h-screen'>
					<ThemeProvider
						attribute='class'
						defaultTheme='system'
						enableSystem
						disableTransitionOnChange
					>
						<AuthProvider>
							<Navigation />
							<MobileNavigation />
							<ChatSupport />
							{children}
						</AuthProvider>
						<Toaster />
					</ThemeProvider>
				</main>
			</body>
		</html>
	);
}
